build:
  version: "@project.version@"

database:
  eventos:
    driver: com.mysql.cj.jdbc.Driver
    connectionString: jdbc:mysql://${database.eventos.database_server}:${database.eventos.database_port}/eventos?useSSL=false&serverTimezone=UTC
    username: root
    password: 5akG-,i+4Vi]B
    autocommit: true
    database_server: localhost
    database_port: 3306
    